### ISSUE TITLE
Slider bar overlaps input field

### ISSUE THREAD

**Issue by YuriGor** [jquery/jquerymobile.com#139] opened 2017-02-25 11:03 UTC
http://demos.jquerymobile.com/1.4.5/forms/
"Slider with fill, mini, track theme"
![image](https://cloud.githubusercontent.com/assets/6861317/23330593/a77a6e42-fb62-11e6-994e-6bab5ca6cdf7.png)

Ubuntu 16.04
Chrome 56.0.2924.87 (64-bit)
Firefox 51.0.1 (64-bit)

**Comment by agcolom** [comment] 2017-02-25 11:35
@YuriGor Thanks for reporting. I will close this issue as it is a a duplicate of https://github.com/jquery/jquery-mobile/issues/7821 and this is now fixed in master. The issue https://github.com/jquery/jquery-mobile/issues/7821 offers a workaround if you need it.

**Closed by agcolom** 2017-02-25 11:35 UTC
