### ISSUE TITLE
jQuery Mobile Download Builder

### ISSUE THREAD

**Issue by satheeshkurup** [jquery/jquerymobile.com#132] opened 2016-05-25 03:56 UTC
http://jquerymobile.com/download-builder/

The page specified is not loading on any browsers. It always shows loading rotator for hours. Urgently I need swipe event from jQuery mobile. 

Thanks,
SK

**Comment by rodrigograca31** [comment] 2016-05-25 09:40
I can confirm this.
It has not worked in the last 15 hours....

The Chrome Console shows the following erros:

```
jquery-1.11.3.js:9664 GET http://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js send @ jquery-1.11.3.js:9664ajax @ jquery-1.11.3.js:9215jQuery.each.jQuery.(anonymous function) @ jquery-1.11.3.js:9361getJSON @ jquery-1.11.3.js:9344refreshForm @ builder.js:149(anonymous function) @ builder.js:185fire @ jquery-1.11.3.js:3148fireWith @ jquery-1.11.3.js:3260ready @ jquery-1.11.3.js:3472completed @ jquery-1.11.3.js:3503
(index):1 XMLHttpRequest cannot load http://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://jquerymobile.com' is therefore not allowed access. The response had HTTP status code 502.
```

Visiting the URL shows a CloudFlare page with this message:

"Website is offline No cached version of this page is available."
"amd-builder.jquerymobile.com
Host
Error

[http://amd-builder.jquerymobile.com/](http://amd-builder.jquerymobile.com/)
`This page (http://amd-builder.jquerymobile.com/) is currently offline. However, because the site uses CloudFlare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by CloudFlare | Hide this Alert`

**Comment by rodrigograca31** [comment] 2016-05-25 09:59
P.S. I need to make a download ASAP.....

**Comment by apsdehal** [comment] 2016-05-25 10:45
We will look into the issue soon. JQM uses https://github.com/gseguin/node-amd-builder for building the downloads. For now if it is very urgent you can use it to get yourself a build.

**Comment by emre-sumer** [comment] 2016-05-26 09:30
Still not working..
jquery-1.11.3.js:9664 GET http://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js 
2016-05-26 12:29:26.789 (index):1 XMLHttpRequest cannot load http://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://jquerymobile.com' is therefore not allowed access. The response had HTTP status code 502.

**Comment by Vassil510** [comment] 2016-05-27 03:36
Same here, Download Builder has been down yesterday and today.

**Comment by CharlieHawker** [comment] 2016-05-27 09:47
+1 still not working.

**Comment by rodrigograca31** [comment] 2016-06-01 12:26
It looks like that it's working now....
@satheeshkurup could you confirm this and close this issue?

**Comment by arschmitz** [comment] 2016-06-01 12:29
Sorry i missed this issue yes there was a problem it kept going down daily we resolved this issue and the builder should be fine now. If any one sees this again please open a new issue.

**Closed by arschmitz** 2016-06-01 12:29 UTC

**Comment by h0n24** [comment] 2020-06-02 09:38
Reopening this due to current Bad Gateway (502) issue:

https://amd-builder.jquerymobile.com/v1/dependencies/jquery/jquery-mobile/1.4.5/?baseUrl=js
